services:
  web:
    build:
      context: .
    command: 
      - sh
      - -c
      - |
        python manage.py migrate
        echo "Migration completed."
        python manage.py collectstatic
        echo "collecting completed."
        gunicorn --bind 0.0.0.0:8000 src.wsgi:application
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
volumes:
  postgres_data:
