# Generated by Django 4.2.4 on 2023-09-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_announcement_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('Хочу научиться', 'Хочу научиться'), ('Могу научить', 'Могу научить')], default='Хочу научиться', max_length=100),
        ),
    ]
